name: Development - Testing

on:
  push:
    branches:
      - 'development'

jobs:
  build:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      # - name: Create the release folder on the server
      #   run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'mkdir /var/www/pullcrm.dev/frontend/versions/release-${{ github.sha }}'

