name: Development - deploy

env:
  NODE_VERSION: 18.16.1

on:
  push:
    branches:
      - 'development'

jobs:
  build:
    name: Build web app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        env:
          GITHUB_SHA: ${{ github.sha }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          # cache: 'yarn'

      - name: Build web app #2
        run: |
          ls -la
          cd web
          touch .env
          echo RELEASE_VERSION=${GITHUB_REF} >> .env
          echo GITHUB_SHA=${GITHUB_SHA} >> .env
          yarn install
          yarn build
          cd ../
          tar -czf web-"${GITHUB_SHA}".tar.gz ./web
          ls -la

      # - name: Store app-artifacts for distribution
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: web-app-artifacts
      #     path: ./web

  # deploy:
  #   name: Deploy web app
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create SSH key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: web-app-artifacts

  #     - name: Upload app-artifacts
  #       run: rsync -avz ./web ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/artifacts/web-"${GITHUB_SHA}"

