version: "3"

volumes:
  node_modules:
services:
  stt-web-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3003:3003"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
